### ISSUE TITLE
Exception "Intention Description Dir URL is null" wiht PhpStorm 2020.2 (RC)

### ISSUE THREAD

**Issue by InvisibleSmiley** [Haehnchen/idea-php-phpunit-plugin#55]
```
com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: PHPUnit; AddMethodIntention; while looking for description.html [Plugin: de.espend.idea.php.phpunit]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:63)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:126)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.processMetaData(IntentionManagerSettings.java:188)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaDataForEp(IntentionManagerSettings.java:92)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.access$000(IntentionManagerSettings.java:32)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.lambda$processOptions$0(IntentionManagerSettings.java:221)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.java:221)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$1(SearchableOptionsRegistrarImpl.java:132)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:132)
	at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

PhpStorm 2020.2
Build #PS-202.6397.71, built on July 23, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, vcs.commit.tool.window=false
Non-Bundled Plugins: CMD Support, Key Promoter X, PlantUML integration, PowerMouse, Realigner, Shifter, String Manipulation, com.alayouni.ansiHighlight, com.andrewbrookins.wrap_to_column, com.intellij.ideolog, com.jetbrains.ChooseRuntime, com.johnlindquist.OpenInDebuggex, com.mnw.permute, com.potterhsu.jsonviewer, com.tabnine.TabNine, de.netnexus.camelcaseplugin, jp.ikeponias, net.seesharpsoft.intellij.plugins.csv, PhpStormRESTControl, com.atlassian.bitbucket.references, com.intellij.lang.puppet, com.vladsch.idea.multimarkdown, NEON support, com.axeldev.php1Up, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.phpunit, lv.midiana.misc.phpstorm-plugins.deep-keys, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, com.aopphp.go.framework, cz.daku.intellij.extraActions, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc

**Comment by evotodi** [comment]
Same issue but on PHPStorm 2020.2 Release

![Annotation 2020-08-10 080015](https://user-images.githubusercontent.com/1625853/89780489-8a3c6f00-dadf-11ea-8a1e-25465e88e8d0.png)

PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Licensed to Justin Davis
Subscription is active until July 2, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1972M
Cores: 24
Registry: projectView.hide.dot.idea=false, run.processes.with.pty=TRUE
Non-Bundled Plugins: CMD Support, Scratch, com.intellij.ideolog, com.github.jk1.ytplugin, net.sjrx.intellij.plugins.systemdunitfiles, mobi.hsz.idea.gitignore, com.perl5, pro.bashsupport, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, com.github.masahirosuzuka.PhoneGapIntelliJPlugin, de.espend.idea.php.phpunit, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv

**Comment by Haehnchen** [comment]
fixed

**Comment by evotodi** [comment]
Thank you.
