### ISSUE TITLE
Exception during plugin update

### ISSUE THREAD

**Issue by garak** [Haehnchen/idea-php-phpunit-plugin#60]
Got following exception while upgrading plugin to 5.0.
PhpStorm 2020.2

>com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: PHPUnit; AddMethodIntention; while looking for description.html [Plugin: de.espend.idea.php.phpunit]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:63)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:126)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.processMetaData(IntentionManagerSettings.java:188)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.registerMetaDataForEp(IntentionManagerSettings.java:92)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings.access$000(IntentionManagerSettings.java:32)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.lambda$processOptions$0(IntentionManagerSettings.java:221)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.java:221)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$1(SearchableOptionsRegistrarImpl.java:132)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:132)
	at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by upyx** [comment]
> Got following exception while upgrading plugin to 5.0.

To 6.0 ...

The same error :disappointed:
